### ISSUE TITLE
compatibility with laravel 5.2.5?

### ISSUE THREAD

**Issue by rohan0793** [antonioribeiro/firewall#41]
I recently upgraded my application to 5.2.5 and soon saw a few errors from the package. I am pasting the stack below here:

```
[2015-12-29 09:23:20] local.ERROR: exception 'BadMethodCallException' with message 'Method filter does not exist.' in /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:81
Stack trace:
#0 /home/vagrant/Code/archive/vendor/pragmarx/firewall/src/Vendor/Laravel/ServiceProvider.php(163): Illuminate\Routing\Router->__call('filter', Array)
#1 /home/vagrant/Code/archive/vendor/pragmarx/firewall/src/Vendor/Laravel/ServiceProvider.php(163): Illuminate\Routing\Router->filter('fw-block-bl', '\\PragmaRX\\Firew...')
#2 /home/vagrant/Code/archive/vendor/pragmarx/firewall/src/Vendor/Laravel/ServiceProvider.php(67): PragmaRX\Firewall\Vendor\Laravel\ServiceProvider->registerFilters()
#3 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(531): PragmaRX\Firewall\Vendor\Laravel\ServiceProvider->register()
#4 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(PragmaRX\Firewall\Vendor\Laravel\ServiceProvider))
#5 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(507): Illuminate\Foundation\ProviderRepository->load(Array)
#6 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#7 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#8 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#9 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#10 /home/vagrant/Code/archive/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 {main}
```

I also posted a question at SO [here](http://stackoverflow.com/questions/34507463/antonioribeiro-firewall-package-throwing-errors-after-upgrading-to-laravel-5-2-5?noredirect=1#comment56758336_34507463)

Now the package is really great, no doubt, but I am guessing it is not compatible with 5.2.5. How do I work around this?

**Comment by mrgswift** [comment]
Hi rohan0793,

Have you updated your firewall to the latest version?  I recently migrated everything to middleware to replace the route filters.  The author merged my changes, so if you updated to version 1.X  it should work.  Refer to the new readme for instructions to set up the middleware.

**Comment by rohan0793** [comment]
Hi,

Thanks for taking the time to reply. I figured I was using an old version and upgraded it to 1.0 but now I am facing another problem also described in the new issue that is just opened [here](https://github.com/antonioribeiro/firewall/issues/42)

I will also still paste the stack over here:

```
[2016-01-04 07:48:13] local.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method [getStubConfigPath]' in /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:235
Stack trace:
#0 /home/vagrant/Code/archive/vendor/pragmarx/support/src/ServiceProvider.php(197): Illuminate\Support\ServiceProvider->__call('getStubConfigPa...', Array)
#1 /home/vagrant/Code/archive/vendor/pragmarx/support/src/ServiceProvider.php(197): PragmaRX\Firewall\Vendor\Laravel\ServiceProvider->getStubConfigPath()
#2 /home/vagrant/Code/archive/vendor/pragmarx/support/src/ServiceProvider.php(79): PragmaRX\Support\ServiceProvider->publishConfig()
#3 [internal function]: PragmaRX\Support\ServiceProvider->boot()
#4 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#5 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#6 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(PragmaRX\Firewall\Vendor\Laravel\ServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(PragmaRX\Firewall\Vendor\Laravel\ServiceProvider), 22)
#8 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#9 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
#13 /home/vagrant/Code/archive/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#14 /home/vagrant/Code/archive/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#15 {main} 
```
